steps:
  - label: ":semgrep: Semgrep OSS"
    key: semgrep
    commands:
      - semgrep scan --config auto
    plugins:
      - docker#v5.11.0:
          image: semgrep/semgrep
  - label: "deploy"
    key: deploy
    commands: 
      - fly deploy -a hello-fastapi
    depends_on: [semgrep]